name: Build Triplane Turmoil Production Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      release_notes:
        required: true
        type: string

jobs:
  create-beta-release:
    name: Create production release
    uses: sergiou87/triplane-turmoil/.github/workflows/build-release.yml@master
    with:
      version: ${{ github.event.inputs.version }}
      release_notes: ${{ github.event.inputs.release_notes }}
      prerelease: false
